import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";

const dist = path.join("src", "widgets", "dist", "index.html");
const outDir = path.join("src", "widgets", "generated");
const html = readFileSync(dist, "utf8");
if (!html.includes("__PARLAY_SITE__")) {
  throw new Error("wrap-widget-html: __PARLAY_SITE__ placeholder missing from built widget");
}
mkdirSync(outDir, { recursive: true });
writeFileSync(
  path.join(outDir, "drill-widget-html.ts"),
  `// GENERATED by scripts/wrap-widget-html.ts — do not edit, do not commit.\n` +
  `export const DRILL_WIDGET_HTML: string = ${JSON.stringify(html)};\n`,
);
console.log(`wrap-widget-html: wrote ${outDir}/drill-widget-html.ts (${html.length} bytes)`);
